{{- if .Values.mcm.enabled -}}
apiVersion: integrations.sdk.cp4mcm.ibm.com/v1beta1
kind: OidcClientRegistration
metadata:
  name: mc-oidcclientregistration
  labels:
    app.kubernetes.io/name: {{ template "hazelcast.name" . }}
    helm.sh/chart: {{ template "hazelcast.chart" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
spec:
  registration:
    post_logout_redirect_uris:
      - http://{{ template "mancenter.fullname" . }}-{{ .Release.Namespace }}.{{ "{{" }} .OpenShiftBaseUrl {{ "}}" }}
    trusted_uri_prefixes:
      - http://{{ template "mancenter.fullname" . }}-{{ .Release.Namespace }}.{{ "{{" }} .OpenShiftBaseUrl {{ "}}" }}
    redirect_uris:
      - http://{{ template "mancenter.fullname" . }}-{{ .Release.Namespace }}.{{ "{{" }} .OpenShiftBaseUrl {{ "}}" }}/oidc/auth
    client_secret:
      secretName: hz-mc-oidc-reg-secret
      secretKey: "1234"
    apply_client_secret: true
{{- end }}